spring:
  profiles:
    active: sc-dev
---
server:
  port: 8201
spring:
  profiles: sc-dev
  application:
    name: sc-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

---

server:
  port: 8202
spring:
  profiles: sc-test
  application:
    name: sc-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
